Update patch set 3
Patch Set 3:

> > > (1 comment)
 > > >
 > > > > At the moment the standalone Buck build doesn't work. Do we
 > > > already
 > > > > have an example for a Buck standalone build for UI plugins?
 > > >
 > > > Just use __standalone_mode__ variables that was recently merged
 > > to
 > > > properly include gwtexpui artifact in standalone mode. And yes,
 > > we
 > > > have working standalone examples for almost everything,
 > > > unfortunately all rejected (no review  activity within 1 month)
 > > > [1]:
 > >
 > > I was afraid that you would say this. Feeling guilty for not
 > having
 > > reviewed this change. Do you want to restore it?
 > >
 > > >
 > > > if __standalone_mode__:
 > > > DEPS = ['//lib/gerrit:gwtexpui']
 > > > else:
 > > > DEPS = [
 > > > '//gerrit-gwtexpui:Clippy',
 > > > '//gerrit-gwtexpui:GlobalKey',
 > > > '//gerrit-gwtexpui:SafeHtml',
 > > > '//gerrit-gwtexpui:UserAgent',
 > > > ]
 > > >
 > > > Where '//lib/gerrit:gwtexpui' references Maven gwtexpui
 > artifact
 > > as
 > > > usually:
 > > >
 > > > maven_jar(
 > > > name = 'gwtexpui',
 > > > id = 'gwtexpui:gwtexpui:1.3.4',
 > > > sha1 = '202a068e9ecfef0fe11e7ed59febc5b778ff575b',
 > > > repository = GERRIT,
 > > > license = 'Apache2.0',
 > > > )
 > > >
 > > > And include DEPS as provided_deps.
 > > >
 > > > [1] https://gerrit-review.googlesource.com/58734
 > >
 > > Thanks. I was already trying something like this before, but I
 > had
 > > trouble to make it work. With patch set 3 (which includes this
 > > change) the standalone Buck build is now failing with
 > >
 > [...]
 > >
 > > Where does this wrong -SNAPSHOT come from?
 > 
 > Does this fixed it: [1] ?
 > 
 > [1] https://gerrit-review.googlesource.com/60752

Thanks!! This fix helps indeed :)

I'm now facing another issue, the used gwtexpui version (1.3.4) is too old and the class CacheHeaders which is contained in it conflicts with the CacheHeaders class that is packaged in the gerrit-plugin-api.

  git/plugins/xdocs/src/main/java/com/googlesource/gerrit/plugins/xdocs/XDocServlet.java:208: error: method setCacheablePrivate in class com.google.gwtexpui.server.CacheHeaders cannot be applied to given types;
          CacheHeaders.setCacheablePrivate(res, 7L, TimeUnit.DAYS, false);
                    ^
    required: javax.servlet.http.HttpServletResponse,long,java.util.concurrent.TimeUnit
    found: javax.servlet.http.HttpServletResponse,long,java.util.concurrent.TimeUnit,boolean
    reason: actual and formal argument lists differ in length
  Errors: 1. Warnings: 0.
  BUILD FAILED: //:x-docs__plugin failed with exit code 1:

For the Maven build and the Buck in tree build the CacheHeaders class from gerrit-plugin-api/gerrit core wins and the build succeeds. The Buck standalone build tries to use the class from gwtexpui and the build fails, because in this class version the setCacheablePrivate doesn't have the mustRevalidate boolean parameter yet....

I guess it's time to publish a new gwtexpui version to Maven Central and then use this new version. Matthias already changed the gwtexpui group ID to prepare this:

  https://gerrit-review.googlesource.com/57788

Patch-set: 3