Update patch set 1
Patch Set 1: Code-Review+1

This fixes one part of the tests :), thanks.

But still fails with

paladox@gerrit-test:~/gerrit$ bazel build plugins/x-docs:x_docs_tests
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home/paladox/gerrit/plugins/x-docs/BUILD:45:1: Java compilation in rule '//plugins/x-docs:x_docs_tests' failed: Worker process sent response with exit code: 1.
plugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/xdocs/formatter/AsciidoctorFormatterTest.java:40: error: cannot find symbol
    expect(util.applyCss(anyString(), anyString(), anyString())).andAnswer(
                         ^
  symbol:   method anyString()
  location: class AsciidoctorFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/xdocs/formatter/AsciidoctorFormatterTest.java:40: error: cannot find symbol
    expect(util.applyCss(anyString(), anyString(), anyString())).andAnswer(
                                      ^
  symbol:   method anyString()
  location: class AsciidoctorFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/xdocs/formatter/AsciidoctorFormatterTest.java:40: error: cannot find symbol
    expect(util.applyCss(anyString(), anyString(), anyString())).andAnswer(
                                                   ^
  symbol:   method anyString()
  location: class AsciidoctorFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/xdocs/formatter/AsciidoctorFormatterTest.java:60: error: cannot find symbol
    expect(formatters.getFormatterConfig(anyString(), anyString())).andReturn(cfg);
                                         ^
  symbol:   method anyString()
  location: class AsciidoctorFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/xdocs/formatter/AsciidoctorFormatterTest.java:60: error: cannot find symbol
    expect(formatters.getFormatterConfig(anyString(), anyString())).andReturn(cfg);
                                                      ^
  symbol:   method anyString()
  location: class AsciidoctorFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/xdocs/formatter/MarkdownFormatterTest.java:41: error: cannot find symbol
    expect(util.getInheritedCss(anyString(), anyString(), anyString(), anyString())).andReturn("");
                                ^
  symbol:   method anyString()
  location: class MarkdownFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/xdocs/formatter/MarkdownFormatterTest.java:41: error: cannot find symbol
    expect(util.getInheritedCss(anyString(), anyString(), anyString(), anyString())).andReturn("");
                                             ^
  symbol:   method anyString()
  location: class MarkdownFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/xdocs/formatter/MarkdownFormatterTest.java:41: error: cannot find symbol
    expect(util.getInheritedCss(anyString(), anyString(), anyString(), anyString())).andReturn("");
                                                          ^
  symbol:   method anyString()
  location: class MarkdownFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/xdocs/formatter/MarkdownFormatterTest.java:41: error: cannot find symbol
    expect(util.getInheritedCss(anyString(), anyString(), anyString(), anyString())).andReturn("");
                                                                       ^
  symbol:   method anyString()
  location: class MarkdownFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/xdocs/formatter/MarkdownFormatterTest.java:53: error: cannot find symbol
    expect(formatters.getFormatterConfig(anyString(), anyString())).andReturn(cfg);
                                         ^
  symbol:   method anyString()
  location: class MarkdownFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/xdocs/formatter/MarkdownFormatterTest.java:53: error: cannot find symbol
    expect(formatters.getFormatterConfig(anyString(), anyString())).andReturn(cfg);
                                                      ^
  symbol:   method anyString()
Target //plugins/x-docs:x_docs_tests failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 107.533s, Critical Path: 85.51s

Patch-set: 1
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=+1