Update patch set 1
Patch Set 1: Verified-1

This is not working yet, trying to format an .docx file fails with a ClassNotFoundException (at least this is the first error).

  ERROR org.docx4j.XmlUtils : Warning: Xalan jar missing from classpath; xslt not supported
  javax.xml.transform.TransformerFactoryConfigurationError: Provider org.apache.xalan.processor.TransformerFactoryImpl not found
  ...
  Caused by: java.lang.ClassNotFoundException: org/apache/xalan/processor/TransformerFactoryImpl
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at javax.xml.transform.FactoryFinder.getProviderClass(FactoryFinder.java:125)
    at javax.xml.transform.FactoryFinder.newInstance(FactoryFinder.java:182)
    at javax.xml.transform.FactoryFinder.find(FactoryFinder.java:250)
    at javax.xml.transform.TransformerFactory.newInstance(TransformerFactory.java:101)
    ... 78 more

I'm confused by this because this class is actually contained in the plugin jar:

  $ tar -tvf ~/site/plugins/xdocs.jar | grep org/apache/xalan/processor/TransformerFactoryImpl
  -rwxrwxrwx  0 0      0           0 Nov 21 10:11 org/apache/xalan/processor/TransformerFactoryImpl.class

Any ideas why this is not working?

Patch-set: 1
Label: Verified=-1