Drop SUBMITTED state
Due to Gerrit core's dropping of the SUBMITTED state in

  0d3cab063408577a8afdae49e3d3e35fdcf1a214

, x-docs no longer compiled [1]. Hence, we follow Gerrit core's
dropping of the SUBMITTED state, to allow compiling against Gerrit
core's master.

[1] The error message was (re-flowed):
  [...]/x-docs/src/main/java/com/googlesource/gerrit/plugins/xdocs/client/ChangeInfo.java:44:
  error: an enum switch case label must be the unqualified name of an
  enumeration constant
        case SUBMITTED:
             ^
See
http://builds.quelltextlich.at/gerrit/nightly/master/2015-07-11/x-docs.jar.build.stderr.txt
http://builds.quelltextlich.at/gerrit/nightly/master/2015-07-11/index.html#x-docs.jar

Change-Id: Ia56572d7943ed85a0de1e0101a692c9cf0886b0d