Add direct dependency on commons-io to plugin definition
Although x-docs provides its own variant of commons-io through the
dependency chain

  x-docs ->
  //plugins/x-docs/lib/docx4j:docx4j_lib ->
  //plugins/x-docs/lib/commons:commons_lib ->
  //plugins/x-docs/lib/commons:io

, compiling the plugin nontheless failed [1] after Gerrit core stopped
providing its version of commons-io. Hence, to make x-docs compile
again, we add a direct dependency on commons-io to the plugin
definition.

[1] The error message was (reformatted for shorter line length):

  [...]/plugins/x-docs/[...]/Formatters.java:43: error:
    package org.apache.commons.io does not exist
  import org.apache.commons.io.FilenameUtils;
                              ^

. For full logs, see

  http://builds.quelltextlich.at/gerrit/nightly/master/2015-08-06/x-docs.jar.build.stderr.txt
  http://builds.quelltextlich.at/gerrit/nightly/master/2015-08-06/index.html#x-docs.jar

Change-Id: I34bbc68e74c3798fb789d571001cf38ee2301b61