Update patch set 10
Patch Set 10:

Tests fail with

paladox@gerrit-test:~/gerrit$ bazel build plugins/x-docs:x_docs_tests
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home/paladox/gerrit/plugins/x-docs/BUILD:45:1: Java compilation in rule '//plugins/x-docs:x_docs_tests' failed: Worker process sent response with exit code: 1.
bazel-out/local-fastbuild/bin/plugins/x-docs/x_docs_testsTestSuite.java:5: error: cannot find symbol
@Suite.SuiteClasses({com.googlesource.gerrit.plugins.x-docs.AsciidoctorFormatterTest.class,com.googlesource.gerrit.plugins.x-docs.MarkdownFormatterTest.class})
                                            ^
  symbol:   class plugins
  location: package com.googlesource.gerritbazel-out/local-fastbuild/bin/plugins/x-docs/x_docs_testsTestSuite.java:5: error: package docs does not exist
@Suite.SuiteClasses({com.googlesource.gerrit.plugins.x-docs.AsciidoctorFormatterTest.class,com.googlesource.gerrit.plugins.x-docs.MarkdownFormatterTest.class})
                                                           ^bazel-out/local-fastbuild/bin/plugins/x-docs/x_docs_testsTestSuite.java:5: error: cannot find symbol
@Suite.SuiteClasses({com.googlesource.gerrit.plugins.x-docs.AsciidoctorFormatterTest.class,com.googlesource.gerrit.plugins.x-docs.MarkdownFormatterTest.class})
                                                                                                                  ^
  symbol:   class plugins
  location: package com.googlesource.gerritbazel-out/local-fastbuild/bin/plugins/x-docs/x_docs_testsTestSuite.java:5: error: package docs does not exist
@Suite.SuiteClasses({com.googlesource.gerrit.plugins.x-docs.AsciidoctorFormatterTest.class,com.googlesource.gerrit.plugins.x-docs.MarkdownFormatterTest.class})
                                                                                                                                 ^plugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/x-docs/AsciidoctorFormatterTest.java:40: error: cannot find symbol
    expect(util.applyCss(anyString(), anyString(), anyString())).andAnswer(
                         ^
  symbol:   method anyString()
  location: class AsciidoctorFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/x-docs/AsciidoctorFormatterTest.java:40: error: cannot find symbol
    expect(util.applyCss(anyString(), anyString(), anyString())).andAnswer(
                                      ^
  symbol:   method anyString()
  location: class AsciidoctorFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/x-docs/AsciidoctorFormatterTest.java:40: error: cannot find symbol
    expect(util.applyCss(anyString(), anyString(), anyString())).andAnswer(
                                                   ^
  symbol:   method anyString()
  location: class AsciidoctorFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/x-docs/AsciidoctorFormatterTest.java:60: error: cannot find symbol
    expect(formatters.getFormatterConfig(anyString(), anyString())).andReturn(cfg);
                                         ^
  symbol:   method anyString()
  location: class AsciidoctorFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/x-docs/AsciidoctorFormatterTest.java:60: error: cannot find symbol
    expect(formatters.getFormatterConfig(anyString(), anyString())).andReturn(cfg);
                                                      ^
  symbol:   method anyString()
  location: class AsciidoctorFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/x-docs/MarkdownFormatterTest.java:41: error: cannot find symbol
    expect(util.getInheritedCss(anyString(), anyString(), anyString(), anyString())).andReturn("");
                                ^
  symbol:   method anyString()
  location: class MarkdownFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/x-docs/MarkdownFormatterTest.java:41: error: cannot find symbol
    expect(util.getInheritedCss(anyString(), anyString(), anyString(), anyString())).andReturn("");
                                             ^
  symbol:   method anyString()
  location: class MarkdownFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/x-docs/MarkdownFormatterTest.java:41: error: cannot find symbol
    expect(util.getInheritedCss(anyString(), anyString(), anyString(), anyString())).andReturn("");
                                                          ^
  symbol:   method anyString()
  location: class MarkdownFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/x-docs/MarkdownFormatterTest.java:41: error: cannot find symbol
    expect(util.getInheritedCss(anyString(), anyString(), anyString(), anyString())).andReturn("");
                                                                       ^
  symbol:   method anyString()
  location: class MarkdownFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/x-docs/MarkdownFormatterTest.java:53: error: cannot find symbol
    expect(formatters.getFormatterConfig(anyString(), anyString())).andReturn(cfg);
                                         ^
  symbol:   method anyString()
  location: class MarkdownFormatterTestplugins/x-docs/src/test/java/com/googlesource/gerrit/plugins/x-docs/MarkdownFormatterTest.java:53: error: cannot find symbol
    expect(formatters.getFormatterConfig(anyString(), anyString())).andReturn(cfg);
                                                      ^
  symbol:   method anyString()
  location: class MarkdownFormatterTestTarget //plugins/x-docs:x_docs_tests failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 22.462s, Critical Path: 16.69s


not sure how to fix it though.

Patch-set: 10
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>